---
- name: Ensure Docker Configuration and Prevent Configuration Drift
  hosts: my_group
  become: true

  tasks:
    - name: Install pre-requisite packages
      yum:
        name: "{{ item }}"
        state: latest
      loop:
        - device-mapper-persistent-data
        - lvm2
        - net-tools
        - bind-utils
        - iftop

    - name: Add Docker CE repo
      get_url:
        url: https://download.docker.com/linux/centos/docker-ce.repo
        dest: /etc/yum.repos.d/docker-ce.repo

    - name: Install Docker
      yum:
        name: docker
        state: latest

    - name: Start and enable the Docker daemon
      service:
        name: docker
        state: started
        enabled: yes

    - name: Add centos user to the docker group
      user:
        name: centos
        groups: docker
        append: yes

    - name: Reset connection so docker group is picked up
      meta: reset_connection

    - name: Ensure firewalld service is started and enabled
      service:
        name: firewalld
        state: started
        enabled: true

    - name: Copy Docker Swarm configuration
      copy:
        src: /etc/docker/daemon.json
        dest: /etc/docker/daemon.json
        owner: root
        group: root
        mode: '0644'

