apiVersion: apps/v1
kind: Deployment
metadata:
  name: labl-step3-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: labl-step3
  template:
    metadata:
      labels:
        app: labl-step3
    spec:
      containers:
      - name: labl-step3
        image: sgan1981a/labl_step3:v2.0

        ports:
        - containerPort: 80

